version: 1
build:
  binary: kentchaind
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: alice
    coins:
      - 100000000000000000000000ukent
      - 100000000000000000000000uatom
  - name: bob
    coins:
      - 100000000000000000000000ukent
      - 100000000000000000000000uatom
  - name: david
    coins:
      - 100000000000000000000000ukent
      - 100000000000000000000000uatom
  - name: facuet
    address: kent1yf0eejsuhjc5s3n7xzr0e8fzss6lgpdqsqsenr
    coins:
      - 10000000000000000000000000000ukent
      - 10000000000000000000000000000uatom
      
faucet:
  name: david
  coins:
    - 10ukent
  host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: ukent
    evm:
      params:
        evm_denom: ukent
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: ukent
    mint:
      params:
        mint_denom: ukent
    staking:
      params:
        bond_denom: ukent
  chain_id: kent_1819-1
  consensus_params:
    block:
      max_gas: "100000000"
validators:
  - name: alice
    bonded: 10000000000000000000000ukent
    app:
      evm-rpc:
        address: 0.0.0.0:8545
        ws-address: 0.0.0.0:8546
    home: $HOME/.kentchaind
client:
  openapi:
    path: "docs/static/openapi.yml"
